# Generated by Django 2.1.7 on 2019-03-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
