language: python # => 1
python: # => 2
    - "3.6"
env: # => 4
    -DJANGO=2.1.5
    -DJANGO_SETTINGS_MODULE = test_settings
install: # => 5
    - pip install -r requirements-travis.txt
script: # => 7
<<<<<<< HEAD
    - pytest
=======
    - python manage.py test
>>>>>>> master
