language: python # => 1
python: # => 2
    - "3.6"
    - "3.7"
env: # => 4
    -DJANGO=2.1.5
    -DJANGO_SETTINGS_MODULE = test_settings
install: # => 5
    - pip install -r requirements.txt
script: # => 7
<<<<<<< HEAD
    - python manage.py test
=======
    - pytest
>>>>>>> 685ad0957f314ecab4bd6a871e82f5861af7ebd1
