language: python # => 1
python: # => 2
    - "3.6"
env: # => 4
    -DJANGO=2.2
    -DJANGO_SETTINGS_MODULE = test_settings
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
#before_install:
#    - sudo apt-get -y install sqlite3=3.8.3
install: # => 5
    - pip install -q Django==$DJANGO
    - pip install -r requirements-travis.txt
script: # => 7
    - python manage.py test
