# Generated by Django 2.1.7 on 2019-03-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
