# Generated by Django 2.1.7 on 2019-03-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20190320_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
