# Generated by Django 2.1.7 on 2019-03-22 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20190320_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
