# Generated by Django 2.1.5 on 2019-04-16 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0007_auto_20190321_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('message_content', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('subject', models.CharField(default='Message Subject', max_length=1000)),
            ],
        ),
    ]
